### ISSUE TITLE
Code from custom validators not listed in OpenAPI

### ISSUE THREAD

**Issue by mdefeche** [ghazi-git/drf-standardized-errors#15]
Now that you've integrated this lib so nicely with drf-spectacular, it makes me want to better document the errors

I'm trying to have a complete list of error codes for most fields but I faced an issue with custom validators.

Here's a validator example. 
```
class UniqueInListValidator:
    message = _('The list must contain unique elements.')
    code = "unique"

    def __call__(self, list):
        if len(list) != len(set(list)):
            raise serializers.ValidationError(code=self.code, detail=self.message)
```
I would expect the fields that have this validator applied, to list `unique` as a possible error code. However it doesn't. I guess it would be possible to override `get_serializer_field_error_codes` but ideally this should be handled by the lib.

Any thoughts on this ?

**Comment by ghazi-git** [comment]
I think what you're suggesting makes sense. However, it means adding support for validators that are defined as classes and that have a `code` attribute. That should be a good start for now. Also, I think it will simplify a little the collection of error codes from validators. So, I'll go ahead and implement it.

For the future, I'm considering adding a decorator (sth like `extend_validation_errors` in the style of drf-spectacular) that allows adding error codes for specific fields. It could be helpful when using function-based validators, if the serializer being inspected is from a third party app and the error code is not added to the `serializer.error_messages` or even when raising a `ValidationError` in the view directly.

For now, to add error codes for a specific field, you can check [this entry in the docs](https://drf-standardized-errors.readthedocs.io/en/latest/openapi.html#customize-error-codes-on-an-operation-basis).

**Comment by mdefeche** [comment]
Thanks for the hard work :-)

I've just discovered that error_messages can be passed as param to the field and will enrich the error codes. So the following is an acceptable work around.
```
    codes = serializers.ListField(
        child=serializers.CharField(),
        validators=[UniqueInListValidator()],
        error_messages={UniqueInListValidator.code: UniqueInListValidator.message},
    )
```

If too many errors are reported this way it can rapidly become messy though. So even in this situation an `extend_validation_errors` decorator would make sense to have the documentation out of field declarations.

**Comment by ghazi-git** [comment]
[v0.12.2](https://github.com/ghazi-git/drf-standardized-errors/releases/tag/v0.12.2) adds support for automatically adding the code of custom validators to the possible error codes of a field. The decorator should be part of a future release.
