### ISSUE TITLE
Issue with 403 in specs

### ISSUE THREAD

**Issue by TheSuperiorStanislav** [ghazi-git/drf-standardized-errors#25]
Hi, I discovered an issue when testing via https://github.com/snok/drf-openapi-tester

`403` is not appearing in the specs if I'm using Permissions that are inherited from `AllowAny` or `IsAuthenticated`

Examples
```
class RestrictCRUDOnPublic(
    RestrictCRUDOnPublicMixin,
    permissions.AllowAny,
):
    """Forbid editing if it is not public schema."""


class RestrictCRUDOnPublicAndIsAuthenticated(
    RestrictCRUDOnPublicMixin,
    permissions.IsAuthenticated,
):
    """Forbid editing for not authenticated if it is not public schema."""
```

While  `permissions.AllowAny` can be fixed by simply using `BasePermission`, `permissions.IsAuthenticated` can't be fixed that way.

Suggest checking directly for type in here 
```python
type(permissions[0]) == AllowAny
type(permissions[0]) == IsAuthenticated
```
![image](https://user-images.githubusercontent.com/43534015/210041614-5172d4ed-d499-4e25-b701-fbcd47646a9b.png)

**Comment by ghazi-git** [comment]
You raise a valid point especially for `IsAuthenticated`. Thanks for raising the issue and for the fix
