### ISSUE TITLE
Do not generate errors for read only fields

### ISSUE THREAD

**Issue by TheSuperiorStanislav** [ghazi-git/drf-standardized-errors#27]
Errors for fields are still being generated in specs for 400 response if field itself is serializer and it's fields are not read-only. Am I missing something?

Example
```python

class AnimeSerializer(ModelBaseSerializer):
    """Serializer to show info about anime."""

    class Meta:
        model = models.Anime
        fields = (
            "id",
            "created",
            "modified",
            "image",
            "trailer_youtube_id",
            "title_eng",
            "title_jpn",
            "type",
            "status",
            "source",
            "airing",
            "aired",
            "rating",
            "season",
            "synopsis",
            "background",
            "broadcast_day",
            "broadcast_time",
            "broadcast_timezone",
            "studios",
            "studios_data",
            "genres",
            "genres_data",
        )

class RecommendationSerializer(ModelBaseSerializer):
    """Serializer to show info about recommendation."""

    liked_data = AnimeSerializer(
        source="liked",
        read_only=True,
    )

    recommend_data = AnimeSerializer(
        source="recommend",
        read_only=True,
    )

    class Meta:
        model = models.Recommendation
        fields = (
            "id",
            "created",
            "modified",
            "reason",
            "liked",
            "recommend",
            "liked_data",
            "recommend_data",
            "recommended_by_data",
        )
```
Example of spec
![image](https://user-images.githubusercontent.com/43534015/210042748-262b7379-db80-421a-812c-f524bf530995.png)
![image](https://user-images.githubusercontent.com/43534015/210042830-1a05b352-fc38-48f3-bc86-9e99c4cae289.png)

**Comment by ghazi-git** [comment]
I'll need to double check this and get back to you (probably next week), I thought I had accounted for it https://github.com/ghazi-git/drf-standardized-errors/blob/fea330b75335c5a537162f6573877be6094212d3/drf_standardized_errors/openapi_utils.py#L129

**Comment by TheSuperiorStanislav** [comment]
> I'll need to double check this and get back to you (probably next week), I thought I had accounted for it
> 
> https://github.com/ghazi-git/drf-standardized-errors/blob/fea330b75335c5a537162f6573877be6094212d3/drf_standardized_errors/openapi_utils.py#L129

I took a look and found a way to fix it. The issue was that this function was just checking a field itself, but not its parents and so on. I added a check for it in `get_flat_serializer_fields` and opened pr for it
