### ISSUE TITLE
Integration with DRF-Spectacular seems to break OpenAPI CLI Generator client generation

### ISSUE THREAD

**Issue by uranderu** [ghazi-git/drf-standardized-errors#31]
Hi,
First of all, thank you for your integration with drf-spectacular.
If I can get this to work it would be so cool and a huge timesaver.

So I came across your package when looking for a way to integrate my serializer errors in the OpenAPI schema. I followed your documentation and the schema looks fine to me (but I'm new to this whole OpenAPI thing though). But when I want to generate the API client for my front-end using the [OpenAPI CLI Generator](https://openapi-generator.tech/), the console in my front-end shows the following error:
`SyntaxError: ambiguous indirect export: ParseErrorResponse`
I'm using the [typescript-fetch](https://openapi-generator.tech/docs/generators/typescript-fetch) generator and after looking into the error I noticed the following errors is some of the error models it now generates:
`TS1444: 'V1DashboardLoginCreateValidationError' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.`
For your reference, my schema:
```
openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
  description: |
    # Sample API Description

    Check the [Tips and Tricks](openapi.md#hide-error-responses-that-show-in-every-operation) to understand how to use this sample API description.

    ## Overview
    Here you will probably give an overview of the API and add a description for it.

    ## Authentication
    Since the API requires authentication, you might want to add a section to describe the authentication flow as well.

    ## Errors
    Now this is the important section in this example. In this section, you can list the error responses that appear
    in every operation with some explanation. It can go sth like:

    ### 401 Unauthorized
    These errors are returned with the status code 401 whenever the authentication fails or a request is made to an
    endpoint without providing the authentication information as part of the request. Here are the 2 possible errors
    that can be returned.
    ```json
    {
        "type": "client_error",
        "errors": [
            {
                "code": "authentication_failed",
                "detail": "Incorrect authentication credentials.",
                "attr": null
            }
        ]
    }
    ```
    ```json
    {
        "type": "client_error",
        "errors": [
            {
                "code": "not_authenticated",
                "detail": "Authentication credentials were not provided.",
                "attr": null
            }
        ]
    }
    ```

    ### 405 Method Not Allowed
    This is returned when an endpoint is called with an unexpected http method. For example, if updating a user requires
    a POST request and a PATCH is issued instead, this error is returned. Here's how it looks like:

    ```json
    {
        "type": "client_error",
        "errors": [
            {
                "code": "method_not_allowed",
                "detail": "Method “patch” not allowed.",
                "attr": null
            }
        ]
    }
    ```

    ### 406 Not Acceptable
    This is returned if the `Accept` header is submitted and contains a value other than `application/json`. Here's how the response would look:

    ```json
    {
        "type": "client_error",
        "errors": [
            {
                "code": "not_acceptable",
                "detail": "Could not satisfy the request Accept header.",
                "attr": null
            }
        ]
    }
    ```

    ### 415 Unsupported Media Type
    This is returned when the request content type is not json. Here's how the response would look:

    ```json
    {
        "type": "client_error",
        "errors": [
            {
                "code": "not_acceptable",
                "detail": "Unsupported media type “application/xml” in request.",
                "attr": null
            }
        ]
    }
    ```

    ### 500 Internal Server Error
    This is returned when the API server encounters an unexpected error. Here's how the response would look:

    ```json
    {
        "type": "server_error",
        "errors": [
            {
                "code": "error",
                "detail": "A server error occurred.",
                "attr": null
            }
        ]
    }
    ```
paths:
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - {}
      responses:
        '400':
          content:
            application/vnd.oai.openapi:
              schema:
                $ref: '#/components/schemas/ApiSchemaRetrieveErrorResponse400'
            application/yaml:
              schema:
                $ref: '#/components/schemas/ApiSchemaRetrieveErrorResponse400'
            application/vnd.oai.openapi+json:
              schema:
                $ref: '#/components/schemas/ApiSchemaRetrieveErrorResponse400'
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSchemaRetrieveErrorResponse400'
          description: ''
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /v1/dashboard/login:
    post:
      operationId: v1_dashboard_login_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1DashboardLoginCreateErrorResponse400'
          description: ''
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
          description: ''
  /v1/dashboard/register:
    post:
      operationId: v1_dashboard_register_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1DashboardRegisterCreateErrorResponse400'
          description: ''
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /v1/dashboard/users/{id}/:
    get:
      operationId: v1_dashboard_users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1DashboardUsersRetrieveErrorResponse400'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
              examples:
                NotFound:
                  value:
                    type: client_error
                    errors:
                    - code: not_found
                      detail: Not found.
                      attr: null
          description: ''
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: v1_dashboard_users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1DashboardUsersUpdateErrorResponse400'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
              examples:
                NotFound:
                  value:
                    type: client_error
                    errors:
                    - code: not_found
                      detail: Not found.
                      attr: null
          description: ''
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: v1_dashboard_users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1DashboardUsersPartialUpdateErrorResponse400'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
              examples:
                NotFound:
                  value:
                    type: client_error
                    errors:
                    - code: not_found
                      detail: Not found.
                      attr: null
          description: ''
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: v1_dashboard_users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      responses:
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1DashboardUsersDestroyErrorResponse400'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse404'
              examples:
                NotFound:
                  value:
                    type: client_error
                    errors:
                    - code: not_found
                      detail: Not found.
                      attr: null
          description: ''
        '204':
          description: No response body
components:
  schemas:
    ApiSchemaRetrieveErrorResponse400:
      oneOf:
      - $ref: '#/components/schemas/ParseErrorResponse'
      discriminator:
        propertyName: type
        mapping:
          client_error: '#/components/schemas/ParseErrorResponse'
    ClientErrorEnum:
      enum:
      - client_error
      type: string
    Error404:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode404Enum'
        detail:
          type: string
        attr:
          type: string
          nullable: true
      required:
      - attr
      - code
      - detail
    ErrorCode404Enum:
      enum:
      - not_found
      type: string
    ErrorResponse404:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ClientErrorEnum'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error404'
      required:
      - errors
      - type
    Login:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          maxLength: 150
        password:
          type: string
          maxLength: 128
      required:
      - password
      - username
    ParseError:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ParseErrorCodeEnum'
        detail:
          type: string
        attr:
          type: string
          nullable: true
      required:
      - attr
      - code
      - detail
    ParseErrorCodeEnum:
      enum:
      - parse_error
      type: string
    ParseErrorResponse:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ClientErrorEnum'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ParseError'
      required:
      - errors
      - type
    PatchedUser:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        date_joined:
          type: string
          format: date-time
        date_updated:
          type: string
          format: date-time
          readOnly: true
    Register:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        password:
          type: string
          maxLength: 128
        email:
          type: string
          format: email
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
      required:
      - email
      - password
      - username
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        first_name:
          type: string
          maxLength: 150
        last_name:
          type: string
          maxLength: 150
        date_joined:
          type: string
          format: date-time
        date_updated:
          type: string
          format: date-time
          readOnly: true
      required:
      - date_updated
      - email
      - username
    V1DashboardLoginCreateError:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardLoginCreateNonFieldErrorsErrorComponent'
      - $ref: '#/components/schemas/V1DashboardLoginCreateUsernameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardLoginCreatePasswordErrorComponent'
      discriminator:
        propertyName: attr
        mapping:
          non_field_errors: '#/components/schemas/V1DashboardLoginCreateNonFieldErrorsErrorComponent'
          username: '#/components/schemas/V1DashboardLoginCreateUsernameErrorComponent'
          password: '#/components/schemas/V1DashboardLoginCreatePasswordErrorComponent'
    V1DashboardLoginCreateErrorResponse400:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardLoginCreateValidationError'
      - $ref: '#/components/schemas/ParseErrorResponse'
      discriminator:
        propertyName: type
        mapping:
          validation_error: '#/components/schemas/V1DashboardLoginCreateValidationError'
          client_error: '#/components/schemas/ParseErrorResponse'
    V1DashboardLoginCreateNonFieldErrorsErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - non_field_errors
          type: string
        code:
          enum:
          - invalid
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardLoginCreatePasswordErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - password
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardLoginCreateUsernameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - username
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardLoginCreateValidationError:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ValidationErrorEnum'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/V1DashboardLoginCreateError'
      required:
      - errors
      - type
    V1DashboardRegisterCreateEmailErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - email
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          - unique
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardRegisterCreateError:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardRegisterCreateNonFieldErrorsErrorComponent'
      - $ref: '#/components/schemas/V1DashboardRegisterCreateUsernameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardRegisterCreatePasswordErrorComponent'
      - $ref: '#/components/schemas/V1DashboardRegisterCreateEmailErrorComponent'
      - $ref: '#/components/schemas/V1DashboardRegisterCreateFirstNameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardRegisterCreateLastNameErrorComponent'
      discriminator:
        propertyName: attr
        mapping:
          non_field_errors: '#/components/schemas/V1DashboardRegisterCreateNonFieldErrorsErrorComponent'
          username: '#/components/schemas/V1DashboardRegisterCreateUsernameErrorComponent'
          password: '#/components/schemas/V1DashboardRegisterCreatePasswordErrorComponent'
          email: '#/components/schemas/V1DashboardRegisterCreateEmailErrorComponent'
          first_name: '#/components/schemas/V1DashboardRegisterCreateFirstNameErrorComponent'
          last_name: '#/components/schemas/V1DashboardRegisterCreateLastNameErrorComponent'
    V1DashboardRegisterCreateErrorResponse400:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardRegisterCreateValidationError'
      - $ref: '#/components/schemas/ParseErrorResponse'
      discriminator:
        propertyName: type
        mapping:
          validation_error: '#/components/schemas/V1DashboardRegisterCreateValidationError'
          client_error: '#/components/schemas/ParseErrorResponse'
    V1DashboardRegisterCreateFirstNameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - first_name
          type: string
        code:
          enum:
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardRegisterCreateLastNameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - last_name
          type: string
        code:
          enum:
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardRegisterCreateNonFieldErrorsErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - non_field_errors
          type: string
        code:
          enum:
          - invalid
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardRegisterCreatePasswordErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - password
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardRegisterCreateUsernameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - username
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          - unique
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardRegisterCreateValidationError:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ValidationErrorEnum'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/V1DashboardRegisterCreateError'
      required:
      - errors
      - type
    V1DashboardUsersDestroyErrorResponse400:
      oneOf:
      - $ref: '#/components/schemas/ParseErrorResponse'
      discriminator:
        propertyName: type
        mapping:
          client_error: '#/components/schemas/ParseErrorResponse'
    V1DashboardUsersPartialUpdateDateJoinedErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - date_joined
          type: string
        code:
          enum:
          - date
          - invalid
          - make_aware
          - 'null'
          - overflow
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersPartialUpdateEmailErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - email
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          - unique
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersPartialUpdateError:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardUsersPartialUpdateNonFieldErrorsErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersPartialUpdateUsernameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersPartialUpdateEmailErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersPartialUpdateFirstNameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersPartialUpdateLastNameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersPartialUpdateDateJoinedErrorComponent'
      discriminator:
        propertyName: attr
        mapping:
          non_field_errors: '#/components/schemas/V1DashboardUsersPartialUpdateNonFieldErrorsErrorComponent'
          username: '#/components/schemas/V1DashboardUsersPartialUpdateUsernameErrorComponent'
          email: '#/components/schemas/V1DashboardUsersPartialUpdateEmailErrorComponent'
          first_name: '#/components/schemas/V1DashboardUsersPartialUpdateFirstNameErrorComponent'
          last_name: '#/components/schemas/V1DashboardUsersPartialUpdateLastNameErrorComponent'
          date_joined: '#/components/schemas/V1DashboardUsersPartialUpdateDateJoinedErrorComponent'
    V1DashboardUsersPartialUpdateErrorResponse400:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardUsersPartialUpdateValidationError'
      - $ref: '#/components/schemas/ParseErrorResponse'
      discriminator:
        propertyName: type
        mapping:
          validation_error: '#/components/schemas/V1DashboardUsersPartialUpdateValidationError'
          client_error: '#/components/schemas/ParseErrorResponse'
    V1DashboardUsersPartialUpdateFirstNameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - first_name
          type: string
        code:
          enum:
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersPartialUpdateLastNameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - last_name
          type: string
        code:
          enum:
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersPartialUpdateNonFieldErrorsErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - non_field_errors
          type: string
        code:
          enum:
          - invalid
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersPartialUpdateUsernameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - username
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          - unique
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersPartialUpdateValidationError:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ValidationErrorEnum'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/V1DashboardUsersPartialUpdateError'
      required:
      - errors
      - type
    V1DashboardUsersRetrieveErrorResponse400:
      oneOf:
      - $ref: '#/components/schemas/ParseErrorResponse'
      discriminator:
        propertyName: type
        mapping:
          client_error: '#/components/schemas/ParseErrorResponse'
    V1DashboardUsersUpdateDateJoinedErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - date_joined
          type: string
        code:
          enum:
          - date
          - invalid
          - make_aware
          - 'null'
          - overflow
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersUpdateEmailErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - email
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          - unique
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersUpdateError:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardUsersUpdateNonFieldErrorsErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersUpdateUsernameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersUpdateEmailErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersUpdateFirstNameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersUpdateLastNameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardUsersUpdateDateJoinedErrorComponent'
      discriminator:
        propertyName: attr
        mapping:
          non_field_errors: '#/components/schemas/V1DashboardUsersUpdateNonFieldErrorsErrorComponent'
          username: '#/components/schemas/V1DashboardUsersUpdateUsernameErrorComponent'
          email: '#/components/schemas/V1DashboardUsersUpdateEmailErrorComponent'
          first_name: '#/components/schemas/V1DashboardUsersUpdateFirstNameErrorComponent'
          last_name: '#/components/schemas/V1DashboardUsersUpdateLastNameErrorComponent'
          date_joined: '#/components/schemas/V1DashboardUsersUpdateDateJoinedErrorComponent'
    V1DashboardUsersUpdateErrorResponse400:
      oneOf:
      - $ref: '#/components/schemas/V1DashboardUsersUpdateValidationError'
      - $ref: '#/components/schemas/ParseErrorResponse'
      discriminator:
        propertyName: type
        mapping:
          validation_error: '#/components/schemas/V1DashboardUsersUpdateValidationError'
          client_error: '#/components/schemas/ParseErrorResponse'
    V1DashboardUsersUpdateFirstNameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - first_name
          type: string
        code:
          enum:
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersUpdateLastNameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - last_name
          type: string
        code:
          enum:
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - surrogate_characters_not_allowed
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersUpdateNonFieldErrorsErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - non_field_errors
          type: string
        code:
          enum:
          - invalid
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersUpdateUsernameErrorComponent:
      type: object
      properties:
        attr:
          enum:
          - username
          type: string
        code:
          enum:
          - blank
          - invalid
          - max_length
          - 'null'
          - null_characters_not_allowed
          - required
          - surrogate_characters_not_allowed
          - unique
          type: string
        detail:
          type: string
      required:
      - attr
      - code
      - detail
    V1DashboardUsersUpdateValidationError:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ValidationErrorEnum'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/V1DashboardUsersUpdateError'
      required:
      - errors
      - type
    ValidationErrorEnum:
      enum:
      - validation_error
      type: string
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
```
I'm using SvelteKit as my front-end with the static adapter and default TypeScript settings. As far as I know this could also be an issue of the "typescript-fetch" plugin of the generator reading the schema wrong.

Thanks in advance!

**Comment by ghazi-git** [comment]
thank you for raising the issue @uranderu. Can you try [swagger editor](https://editor.swagger.io/) instead?
I copied the schema you provided to swagger editor, generated a client using typescript-fetch and the generation didn't error out.
![image](https://user-images.githubusercontent.com/17159441/214381599-373e0de2-0e28-4059-b6bf-b24a6fd387c9.png)

**Comment by uranderu** [comment]
Hi,
On my side the generation also doesn't error out. The error in my console I get when navigating to the pages that use the API client and the TS errors I get when inspecting the models in my IDE.

**Comment by uranderu** [comment]
The files it generates though are different, so this is another kind of generator. I'll see if I can use that instead. However in the mean time, I also tried my schema in the new Swagger Editor and there some issues popped up:
![image](https://user-images.githubusercontent.com/71091366/214385819-bd7fe079-ac1f-4058-800f-2b1cf279a948.png)
In case it isn't readable, it gives errors on some of the error components saying that "Oneof" must be a non-empty array. Currently it's structured like this:
```
      oneOf:
      - $ref: '#/components/schemas/V1DashboardLoginCreateNonFieldErrorsErrorComponent'
      - $ref: '#/components/schemas/V1DashboardLoginCreateUsernameErrorComponent'
      - $ref: '#/components/schemas/V1DashboardLoginCreatePasswordErrorComponent'
```

**Comment by ghazi-git** [comment]
I missed the warnings because I wasn't using the new version of that editor.
 
After some googling, it turns out the errors displayed in the new editor correspond to a bug https://github.com/swagger-api/swagger-editor/issues/3722

I also tried the example from [their docs](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#oneof) in the new editor and saw the same error.
![image](https://user-images.githubusercontent.com/17159441/214407153-d5adb81a-ce02-4809-8562-ea2e054b3d19.png)
 
So, I think you can ignore those errors.

**Comment by uranderu** [comment]
Alright, after some more testing I think I found the culprit. So SvelteKit by default in their tsconfig, enable the "preserveValueImports" compiler option. I don't know why, but after disabling it (which is the TS default) I don't get any errors and everything worked as before. Thank you for your help and fast responses.
