### ISSUE TITLE
Missing py.typed file

### ISSUE THREAD

**Issue by PedroPerpetua** [ghazi-git/drf-standardized-errors#32]
Even though the code base appears to be fully typed, linters like mypy fail to correctly type-check applications that use this package due to missing the py.typed file.

More details can be found here: https://mypy.readthedocs.io/en/stable/running_mypy.html?highlight=py.typed#missing-library-stubs-or-py-typed-marker

Simply adding a py.typed file to the pip packaging should fix the issue.

**Comment by PedroPerpetua** [comment]
Relevant PEP: https://peps.python.org/pep-0561/#packaging-type-information

**Comment by ghazi-git** [comment]
I actually didn't think about mypy when adding type hints. I mostly added them to get intelli-sense from IDEs and make it a little easier to maintain the package. Now, I'm interested in learning more about mypy and add some of the missing type hints as well. So, thank you for opening the issue, I'll try to look into it during the weekend.
