### ISSUE TITLE
drf-spectacular integration @extend_schema_serializer() examples not work

### ISSUE THREAD

**Issue by mikucz** [ghazi-git/drf-standardized-errors#65]
In drf-spectacular `AutoSchema` class we have function `_get_examples()` with following code:

```python
#...
# don't let the parameter examples influence the serializer example retrieval
examples = [e for e in self.get_examples() if not e.parameter_only]

# Examples from Serializers via @extend_schema_serializer are only considered, if
# there were no higher priority examples directly from view annotation.
if not examples:
    if is_list_serializer(serializer):
        examples = get_override(serializer.child, 'examples', [])
    elif is_serializer(serializer):
        examples = get_override(serializer, 'examples', [])
#...
``` 
direct link: https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/openapi.py#L1217

Since drf-standarized-errors overrides `get_examples()` in overwritten `AutoSchema` version with examples from exceptions without `parameters_only` that if statement is not triggered and all `@extend_schem_serializer` examples are ignored.

Solution for that would be to add `parameter_only` value to `get_example_from_exception()` function:
```python
def get_example_from_exception(exc: exceptions.APIException) -> OpenApiExample:
    if is_client_error(exc.status_code):
        type_ = "client_error"
    else:
        type_ = "server_error"
    return OpenApiExample(
        exc.__class__.__name__,
        value={
            "type": type_,
            "errors": [{"code": exc.get_codes(), "detail": exc.detail, "attr": None}],
        },
        response_only=True,
+       parameter_only=("errors", "query"),
        status_codes=[str(exc.status_code)],
    )

```

What do you think @ghazi-git ? If that's ok with you I can prepare PR for that.

One concern that I have is what value provide for this parameter. In docs it is only mentioned here:
https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.utils.OpenApiExample
and here is the list where it is used in drf-spectacular project:
```
openapi.py|276 col 24| if example.parameter_only:
openapi.py|277 col 41| examples_by_key[example.parameter_only].append(example)
openapi.py|1213 col 61| examples = [e for e in self.get_examples() if not e.parameter_only]
```
So in order to fix this issue we need to provide  basically any value to that parameter in `get_example_from_exception()`

<details>
  <summary>Problem screenshots and example code</summary>

  ```python
from rest_framework import serializers
from drf_spectacular.utils import (
    OpenApiExample,
    extend_schema_serializer,
)

@extend_schema_serializer(
    component_name="UserDetailOutputSerializer",
    examples=[
        OpenApiExample(
            "Basic example",
            value={"id": "id", "email": "mail"},
            request_only=False,
            response_only=True,
        ),
    ],
)
class OutputSerializer(serializers.Serializer[Any]):
    id = serializers.UUIDField()
    email = serializers.EmailField()
    first_name = serializers.CharField(max_length=150)
    last_name = serializers.CharField(max_length=150)
  ```
  #### Without `parameter_only`
  
![image](https://github.com/ghazi-git/drf-standardized-errors/assets/37776903/c04520c7-dcea-4da0-bfb1-0bfb929295aa)

  #### With `parameter_only=('errorrs', 'query')`
    
![image](https://github.com/ghazi-git/drf-standardized-errors/assets/37776903/254eb292-7020-4861-b5be-d0490bc6bd05)

</details>

**Comment by ghazi-git** [comment]
Thanks for reporting the issue and sorry I didn't get to this earlier.

I went ahead and pushed a fix for this issue in #69. Now, error response examples are added using the `extras` argument in `AutoSchema._get_examples` instead of adding them under `AutoSchema.get_examples`. Marking the examples as `parameter_only` is a quick workaround but those seem to be a [different type of examples to support specific use cases](https://github.com/tfranzel/drf-spectacular/issues/414#issuecomment-931420836).
