### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by 9128305** [ghazi-git/drf-standardized-errors#66]
Hi, would you mind making a new release?
These changes https://github.com/ghazi-git/drf-standardized-errors/commit/d643791449c1164aa1f757b1c931db731ce698ec are required to use drf-standardized-errors with drf-spectacular 0.27.x.

**Comment by ghazi-git** [comment]
[v0.13.0 is out now](https://github.com/ghazi-git/drf-standardized-errors/releases/tag/v0.13.0)
