### ISSUE TITLE
[OpenApi with drf_spectacular] "Not allowed" status codes are still overriden when manually created.

### ISSUE THREAD

**Issue by PedroPerpetua** [ghazi-git/drf-standardized-errors#73]
My user registration endpoint raises a `403 PermissionDenied("Registration is disabled.")` on some cases.
I wanted this behaviour documented on the OpenAPI spec. In my settings I have selected only 400 errors to be allowed:
```py
DRF_STANDARDIZED_ERRORS = {
    "ALLOWED_ERROR_STATUS_CODES": ["400"]
}
```

I did not find an easy way to detail that my endpoint raises a 403 error that follows the schema defined by `drf-standardized-errors`, with simply changing the detail; this is the expected response:
```py
{
  "type": "client_error",
  "errors": [
    {
      "code": "permission_denied",
      "detail": "Registration is disabled.",
      "attr": null
    }
  ]
```
I looked into the `extend_validation_errors`, but this looks to only work for 400 error codes. As a side note, maybe an easy way to create and specify other errors would be a useful feature?

Either way, I tried to manually extend the OpenAPI schema with `drf_spectacular`'s `extend_schema`:
```py
@extend_schema(responses={403: OpenApiResponse(
    response = {
        'type': 'object',
        'properties': {
            'type': {
                'type': 'string',
                'const': 'client_error',
                'example': 'client_error'
            },
            'errors': {
                'type': 'array',
                'items': {
                    'type': 'object',
                    'properties': {
                        'code': {
                            'type': 'string',
                            'const': 'permission_denied',
                            'example': 'permission_denied'
                        },
                        'detail': {
                            'type': 'string',
                            'const': 'Registration is disabled.',
                            'example': 'Registration is disabled.'
                        },
                        'attr': {
                            'type': ['string', 'null'],
                            'example': None
                        }
                    },
                    'required': ['code', 'detail', 'attr']
                }
            }
        },
        'required': ['type', 'errors']
    },
    description="Registration is disabled"
)})
```

However, the schema still presents the "default standardized error" response, with the wrong detail:
```
{
  "type": "client_error",
  "errors": [
    {
      "code": "permission_denied",
      "detail": "You do not have permission to perform this action.",
      "attr": null
    }
  ]
```
which I don't believe should be the case, given that it's disabled in the settings.

**Comment by ghazi-git** [comment]
Can you first add 403 to the list of `ALLOWED_ERROR_STATUS_CODES`? only responses for those status codes will appear in the API schema
https://github.com/ghazi-git/drf-standardized-errors/blob/8e224befdd5bf45cda775046dfd9f2933ab88108/docs/settings.md?plain=1#L23-L30

**Comment by PedroPerpetua** [comment]
I have tested with and without addingn the status code to the `ALLOWED_ERROR_STATUS_CODES`, but it will always show the "default 403 error" instead of my custom error.

Just to be clear:
- I **do not** want to have 403 codes in all my endpoints (hence why I didn't have 403 in my allowed codes list).
- I'm using `drf_spectacular`'s `extend_schema` method to add a custom 403 response to one of my endpoints.
- It successfully adds as a 403 response to the API Schema; however, instead of it being my custom 403 response, it's the "default" 403 response schema for `drf-standardized-errors`.

It's noteworthy that if I disable `drf-standardized-errors` (by replacing the `REST_FRAMEWORK.DEFAULT_SCHEMA_CLASS` setting back to `drf_spectacular.openapi.AutoSchema`) the schema will correctly display my custom 403 response (though I lose all the other error responses that `drf-standardized-errors` provides.

**Comment by ghazi-git** [comment]
then can you create a custom auto schema class

```python
from drf_standardized_errors.handler import exception_handler as standardized_errors_handler
from drf_standardized_errors.openapi import AutoSchema

class CustomAutoSchema(AutoSchema):
    def get_examples(self):
        # notice how the super call is applied to the parent class bypassing any examples added by drf-standardized-errors
        return super(AutoSchema, self).get_examples()
```

then update your settings
```python
REST_FRAMEWORK = {
    # other settings
    "DEFAULT_SCHEMA_CLASS": "path.to.CustomAutoSchema"
}
```

I think there is an issue with drf-standardized-errors overriding examples coming from responses or `@extend_schema(examples=[...])`. There was a fix related to examples in #69 but it probably doesn't cover your case.

**Comment by ghazi-git** [comment]
I just merged a fix that ensures that error response examples are only added when the corresponding status code is allowed (i.e. the example status code is in `DRF_STANDARDIZED_ERRORS["ALLOWED_ERROR_STATUS_CODES"]` ). This should fix the issue described here.

Also, it is now possible to customize the error response examples for allowed status codes by subclassing `drf_standardized_errors.openapi.AutoSchema` and overriding the new `_get_error_response_examples`

https://github.com/ghazi-git/drf-standardized-errors/blob/e3f781be450c7af22129b10ff7dc7c9decfc769e/drf_standardized_errors/openapi.py#L353-L360

**Comment by PedroPerpetua** [comment]
Great to hear :)
Any expectation on when there will be an official new release? I notice the latest one is about 4 months old, and there's been more fixes.

**Comment by ghazi-git** [comment]
new release ([v0.14.0](https://pypi.org/project/drf-standardized-errors/)) is out
